name: Actions

on:
  push:
    branches:
      - main  # Déclenche l'action sur un push vers la branche main
  pull_request:
    branches:
      - main  # Déclenche l'action sur une Pull Request ouverte vers la branche main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Véerifie le code
        uses: actions/checkout@v2  # Récupére le code source

      - name: Affiche un message
        run: echo "Hello! Le Github actions a été" fait sur windows."

      - name: Vérifie README.md exist
        run: |
          if (Test-Path "README.md") {
            Write-Output "README.md exist."
          } else {
            Write-Error "README.md est introuvable!"
            exit 1
          }
